# Generated by Django 3.0.4 on 2025-04-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0013_remove_prescription_advice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
